
package org.soap.jaxws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://jax_ws_serveur.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://jax_ws_serveur.soap.com/", className = "org.soap.jaxws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://jax_ws_serveur.soap.com/", className = "org.soap.jaxws.TestResponse")
    @Action(input = "http://jax_ws_serveur.soap.com/BanqueService/testRequest", output = "http://jax_ws_serveur.soap.com/BanqueService/testResponse")
    public String test();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDT", targetNamespace = "http://jax_ws_serveur.soap.com/", className = "org.soap.jaxws.ConversionEuroToDT")
    @ResponseWrapper(localName = "ConversionEuroToDTResponse", targetNamespace = "http://jax_ws_serveur.soap.com/", className = "org.soap.jaxws.ConversionEuroToDTResponse")
    @Action(input = "http://jax_ws_serveur.soap.com/BanqueService/ConversionEuroToDTRequest", output = "http://jax_ws_serveur.soap.com/BanqueService/ConversionEuroToDTResponse")
    public double conversionEuroToDT(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
